export {
  getRouteAbout,
  getRouteMain,
  getRouteNotFound,
  getRouteLogin,
  getRouteProfile,
  getRouteRegister,
  getRoutePrivacyPolicy,
  getRouteForbidden,
  getRouteLogout,
  getRouteCreateNote,
  getRouteViewNote,
  getRouteUserViewNotes,
  getRouteSitemap,
  getRouteAdmin,
  getRouteTags,
  getRouteCreateTag,
  getRouteEditTag,
  getRouteCategories,
  getRouteCreateCategory,
  getRouteEditCategory,
  getRouteEditNote,
  getRouteAdminUsers,
  getRouteAdminEditUser,
  getRouteAdminCreateNoteType,
  getRouteAdminNotesTypes,
} from './helpers/routes'
export { AppRoutes } from './types/router'
