export const tinymceCodeLanguagesList = [
  { text: 'HTML/XML', value: 'markup' },
  { text: 'Handlebars', value: 'handlebars' },
  { text: 'Pug', value: 'pug' },
  { text: 'JavaScript', value: 'javascript' },
  { text: 'Typescript', value: 'typescript' },
  { text: 'GraphQL', value: 'graphql' },
  { text: 'JSON', value: 'json' },
  { text: 'CSS', value: 'css' },
  { text: 'Sass', value: 'sass' },
  { text: 'Scss', value: 'scss' },
  { text: 'PHP', value: 'php' },
  { text: 'Ruby', value: 'ruby' },
  { text: 'Python', value: 'python' },
  { text: 'Java', value: 'java' },
  { text: 'C', value: 'c' },
  { text: 'C#', value: 'csharp' },
  { text: 'ASP.NET', value: 'aspnet' },
  { text: 'C++', value: 'cpp' },
  { text: 'Dart', value: 'dart' },
  { text: 'Go', value: 'go' },
  { text: 'Scala', value: 'scala' },
  { text: 'Kotlin', value: 'kotlin' },
  { text: 'Bash (Console command)', value: 'bash' },
  { text: 'Docker', value: 'docker' },
  { text: 'Git', value: 'git' },
  { text: 'Haml', value: 'haml' },
  { text: 'Markdown (MD)', value: 'markdown' },
  { text: 'Sql', value: 'sql' },
  { text: 'Makefile', value: 'makefile' },
  { text: 'Perl', value: 'perl' },
  { text: 'Regex', value: 'regex' },
  { text: 'Yaml', value: 'yaml' },
]
